### ISSUE TITLE
allow slashes in states names

### ISSUE THREAD

**Issue by fredleger** [gi0baro/tfstater#1]
First thanks for this great tool which is by far better than the usual s3 + dynamodb IMHO !

Facing an issue i had some troubles to debug, i realized that you can't use a `/` in a state name (which in http is somewhat logical). But if you look to the traditional s3 it's not the case (a preffix can have subfolders and so on). This is also the way terragrunt is advicing to work.

### with standard config

```hcl
remote_state {
  backend = "http"
  config = {
    address = "https://{tfstater-instance}/terraform/${local.env.name}-${path_relative_to_include()}"
    lock_address = "https://{tfstater-instance}/terraform/${local.env.name}-${path_relative_to_include()}/lock"
    unlock_address = "https://{tfstater-instance}/terraform/${local.env.name}-${path_relative_to_include()}/lock"
    lock_method = "POST"
    unlock_method = "DELETE"
  }
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}
``` 

This will __not__ work if any of the `path_relative_to_include` calls  contains a subfolder

### with patched config

```hcl
remote_state {
  backend = "http"
  config = {
    address = "https://{tfstater-instance}/terraform/${local.env.name}-${replace(path_relative_to_include(), "/", "-")}"
    lock_address = "https://{tfstater-instance}/terraform/${local.env.name}-${replace(path_relative_to_include(), "/", "-")}/lock"
    unlock_address = "https://{tfstater-instance}/terraform/${local.env.name}-${replace(path_relative_to_include(), "/", "-")}/lock"
    lock_method = "POST"
    unlock_method = "DELETE"
  }
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}
```

This will work but is not very readable.

So i was wondering how hard it can be to allow `/` in the states names ? A simpe solution can be to store them urlencoded making `/` transformed in `%2E`.

Any thoughts ?

**Comment by gi0baro** [comment]
> First thanks for this great tool which is by far better than the usual s3 + dynamodb IMHO !

Thank you! :) 

> 
> Facing an issue i had some troubles to debug, i realized that you can't use a `/` in a state name (which in http is somewhat logical). But if you look to the traditional s3 it's not the case (a preffix can have subfolders and so on). This is also the way terragrunt is advicing to work.
> 
> So i was wondering how hard it can be to allow `/` in the states names ? A simpe solution can be to store them urlencoded making `/` transformed in `%2E`.
> 
> Any thoughts ?

I think actually supporting `/` in names wouldn't be so hard. I gonna make some tests locally and see if everything works (the main issue might be urls handling in APIs and views).

I'll update you here during the week!

**Comment by gi0baro** [comment]
@fredleger sorry for the late update. I opened #2 which implements the requested feature.
I gonna run some additional tests, update dependencies and release a new version in the next days

**Comment by fredleger** [comment]
great news let me know when it's ready i can beta test it with a realworld exemple

**Comment by fredleger** [comment]
any news about it ? still offer help to test it

**Comment by fredleger** [comment]
Will give a try thank you

**Comment by gi0baro** [comment]
@fredleger I'm super-sorry for the time this took, but I tested this and 0.3.0 should work :)
